/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Register
(
    input C,
    input en,
    input D,
    output Q
);

    reg  state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Counter_Nbit
#(
    parameter Bits = 2
)
(
    output [(Bits-1):0] out,
    output ovf,
    input C,
    input en,
    input clr
);
    reg [(Bits-1):0] count;

    always @ (posedge C) begin
        if (clr)
          count <= 'h0;
        else if (en)
          count <= count + 1'b1;
    end

    assign out = count;
    assign ovf = en? &count : 1'b0;

    initial begin
        count = 'h0;
    end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_BlockRAMDualPort
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];
  reg [(Bits-1):0] wData;

  assign D = wData;

  always @ (posedge C) begin
    wData <= memory[A];
    if (str)
      memory[A] <= Din;
  end
endmodule


module DIG_CounterPreset #(
    parameter Bits = 2,
    parameter maxValue = 4
)
(
    input C,
    input en,
    input clr,
    input dir,
    input [(Bits-1):0] in,
    input ld,
    output [(Bits-1):0] out,
    output ovf
);

    reg [(Bits-1):0] count = 'h0;

    function [(Bits-1):0] maxVal (input [(Bits-1):0] maxv);
        if (maxv == 0)
            maxVal = (1 << Bits) - 1;
        else
            maxVal = maxv;
    endfunction

    assign out = count;
    assign ovf = ((count == maxVal(maxValue) & dir == 1'b0)
                  | (count == 'b0 & dir == 1'b1))? en : 1'b0;

    always @ (posedge C) begin
        if (clr == 1'b1)
            count <= 'h0;
        else if (ld == 1'b1)
            count <= in;
        else if (en == 1'b1) begin
            if (dir == 1'b0) begin
                if (count == maxVal(maxValue))
                    count <= 'h0;
                else
                    count <= count + 1'b1;
            end
            else begin
                if (count == 'h0)
                    count <= maxVal(maxValue);
                else
                    count <= count - 1;
            end
        end
    end
endmodule


module Mux_8x1_NBits #(
    parameter Bits = 2
)
(
    input [2:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module DIG_Sub #(
    parameter Bits = 2
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits-1):0] s,
    output c_o
);
    wire [Bits:0] temp;

    assign temp = a - b - c_i;
    assign s = temp[(Bits-1):0];
    assign c_o = temp[Bits];
endmodule


module Decoder3 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    input [2:0] sel
);
    assign out_0 = (sel == 3'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 3'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 3'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 3'h3)? 1'b1 : 1'b0;
    assign out_4 = (sel == 3'h4)? 1'b1 : 1'b0;
    assign out_5 = (sel == 3'h5)? 1'b1 : 1'b0;
    assign out_6 = (sel == 3'h6)? 1'b1 : 1'b0;
    assign out_7 = (sel == 3'h7)? 1'b1 : 1'b0;
endmodule


module ALU_OVERTURE (
  input [7:0] INSTRUCTION,
  input [7:0] IN1,
  input [7:0] IN2,
  input [7:0] ADDR,
  input CLK,
  output [7:0] OUT
);
  wire [2:0] s0;
  wire [7:0] s1;
  wire [7:0] s2;
  wire [7:0] s3;
  wire [7:0] s4;
  wire [7:0] s5;
  wire [7:0] s6;
  wire [7:0] s7;
  wire s8;
  assign s0[0] = INSTRUCTION[0];
  assign s0[1] = INSTRUCTION[1];
  assign s0[2] = INSTRUCTION[2];
  assign s1 = (IN1 | IN2);
  assign s2 = ~ (IN1 & IN2);
  assign s3 = ~ (IN1 | IN2);
  assign s4 = (IN1 & IN2);
  DIG_Add #(
    .Bits(8)
  )
  DIG_Add_i0 (
    .a( IN1 ),
    .b( IN2 ),
    .c_i( 1'b0 ),
    .s( s5 )
  );
  DIG_Sub #(
    .Bits(8)
  )
  DIG_Sub_i1 (
    .a( IN1 ),
    .b( IN2 ),
    .c_i( 1'b0 ),
    .s( s6 )
  );
  Decoder3 Decoder3_i2 (
    .sel( s0 ),
    .out_7( s8 )
  );
  DIG_BlockRAMDualPort #(
    .Bits(8),
    .AddrBits(8)
  )
  DIG_BlockRAMDualPort_i3 (
    .A( ADDR ),
    .Din( IN1 ),
    .str( s8 ),
    .C( CLK ),
    .D( s7 )
  );
  Mux_8x1_NBits #(
    .Bits(8)
  )
  Mux_8x1_NBits_i4 (
    .sel( s0 ),
    .in_0( s1 ),
    .in_1( s2 ),
    .in_2( s3 ),
    .in_3( s4 ),
    .in_4( s5 ),
    .in_5( s6 ),
    .in_6( s7 ),
    .in_7( 8'b0 ),
    .out( OUT )
  );
endmodule

module Decoder2 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    input [1:0] sel
);
    assign out_0 = (sel == 2'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 2'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 2'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 2'h3)? 1'b1 : 1'b0;
endmodule


module CompSigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = $signed(a) > $signed(b);
    assign \= = $signed(a) == $signed(b);
    assign \< = $signed(a) < $signed(b);
endmodule


module Mux_8x1
(
    input [2:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    input in_4,
    input in_5,
    input in_6,
    input in_7,
    output reg out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule


module CONDITION (
  input [7:0] INSTRUCTION,
  input [7:0] IN,
  output OUT
);
  wire [2:0] s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  assign s0[0] = INSTRUCTION[0];
  assign s0[1] = INSTRUCTION[1];
  assign s0[2] = INSTRUCTION[2];
  CompSigned #(
    .Bits(8)
  )
  CompSigned_i0 (
    .a( IN ),
    .b( 8'b0 ),
    .\> ( s1 ),
    .\= ( s2 ),
    .\< ( s3 )
  );
  assign s4 = (s3 | s2);
  assign s5 = ~ s2;
  assign s6 = (s1 | s2);
  Mux_8x1 Mux_8x1_i1 (
    .sel( s0 ),
    .in_0( 1'b0 ),
    .in_1( s2 ),
    .in_2( s3 ),
    .in_3( s4 ),
    .in_4( 1'b1 ),
    .in_5( s5 ),
    .in_6( s6 ),
    .in_7( s1 ),
    .out( OUT )
  );
endmodule

module OVERTURE (
  input [7:0] IN,
  input NEXT,
  input EXE,
  input CLK,
  output [7:0] OUT
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire [7:0] s4;
  wire [7:0] s5;
  wire s6;
  wire [7:0] s7;
  wire s8;
  wire [7:0] s9;
  wire [7:0] s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire [7:0] s16;
  wire [1:0] s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire [7:0] s23;
  wire s24;
  wire [7:0] s25;
  wire s26;
  wire [7:0] s27;
  wire s28;
  wire [7:0] s29;
  wire s30;
  wire [7:0] s31;
  wire [7:0] s32;
  wire s33;
  wire s34;
  wire [7:0] s35;
  wire s36;
  wire [7:0] s37;
  wire s38;
  wire [7:0] s39;
  wire [2:0] s40;
  wire [7:0] s41;
  wire [7:0] s42;
  wire [7:0] s43;
  wire [7:0] s44;
  wire [2:0] s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire s50;
  wire s51;
  wire s52;
  wire s53;
  wire [7:0] s54;
  wire [7:0] s55;
  wire s56;
  wire s57;
  wire [7:0] s58;
  DIG_Register DIG_Register_i0 (
    .D( 1'b1 ),
    .C( EXE ),
    .en( 1'b1 ),
    .Q( s12 )
  );
  DIG_Register DIG_Register_i1 (
    .D( 1'b1 ),
    .C( CLK ),
    .en( 1'b1 ),
    .Q( s13 )
  );
  DIG_Register DIG_Register_i2 (
    .D( s13 ),
    .C( CLK ),
    .en( 1'b1 ),
    .Q( s14 )
  );
  assign s22 = ~ s12;
  assign s15 = (1'b1 & (s13 & ~ s14));
  assign s0 = (s15 | NEXT);
  assign s8 = (s12 | s15);
  DIG_Register DIG_Register_i3 (
    .D( s0 ),
    .C( CLK ),
    .en( 1'b1 ),
    .Q( s1 )
  );
  Mux_2x1 Mux_2x1_i4 (
    .sel( s8 ),
    .in_0( s0 ),
    .in_1( 1'b0 ),
    .out( s6 )
  );
  DIG_Register DIG_Register_i5 (
    .D( s1 ),
    .C( CLK ),
    .en( 1'b1 ),
    .Q( s2 )
  );
  assign s3 = (~ s1 & s2);
  DIG_Counter_Nbit #(
    .Bits(8)
  )
  DIG_Counter_Nbit_i6 (
    .en( 1'b1 ),
    .C( s3 ),
    .clr( 1'b0 ),
    .out( s4 )
  );
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i7 (
    .D( IN ),
    .C( s3 ),
    .en( 1'b1 ),
    .Q( s44 )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i8 (
    .sel( s12 ),
    .in_0( 8'b0 ),
    .in_1( s44 ),
    .out( s41 )
  );
  DIG_BlockRAMDualPort #(
    .Bits(8),
    .AddrBits(8)
  )
  DIG_BlockRAMDualPort_i9 (
    .A( s5 ),
    .Din( IN ),
    .str( s6 ),
    .C( CLK ),
    .D( s7 )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i10 (
    .sel( s8 ),
    .in_0( s4 ),
    .in_1( s9 ),
    .out( s5 )
  );
  DIG_CounterPreset #(
    .Bits(8),
    .maxValue(0)
  )
  DIG_CounterPreset_i11 (
    .en( s8 ),
    .C( s3 ),
    .dir( 1'b0 ),
    .in( s10 ),
    .ld( s11 ),
    .clr( 1'b0 ),
    .out( s9 )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i12 (
    .sel( s22 ),
    .in_0( s7 ),
    .in_1( 8'b0 ),
    .out( s16 )
  );
  Mux_8x1_NBits #(
    .Bits(8)
  )
  Mux_8x1_NBits_i13 (
    .sel( s40 ),
    .in_0( s10 ),
    .in_1( s29 ),
    .in_2( s31 ),
    .in_3( s23 ),
    .in_4( s35 ),
    .in_5( s37 ),
    .in_6( s41 ),
    .in_7( s42 ),
    .out( s43 )
  );
  ALU_OVERTURE ALU_OVERTURE_i14 (
    .INSTRUCTION( s16 ),
    .IN1( s29 ),
    .IN2( s31 ),
    .ADDR( s42 ),
    .CLK( s0 ),
    .OUT( s39 )
  );
  assign s58[5:0] = s16[5:0];
  assign s58[6] = 1'b0;
  assign s58[7] = 1'b0;
  assign s17 = s16[7:6];
  assign s40 = s16[5:3];
  assign s45 = s16[2:0];
  Decoder2 Decoder2_i15 (
    .sel( s17 ),
    .out_0( s18 ),
    .out_1( s19 ),
    .out_2( s20 ),
    .out_3( s21 )
  );
  Decoder3 Decoder3_i16 (
    .sel( s45 ),
    .out_0( s46 ),
    .out_1( s47 ),
    .out_2( s48 ),
    .out_3( s49 ),
    .out_4( s50 ),
    .out_5( s51 ),
    .out_6( s52 ),
    .out_7( s53 )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i17 (
    .sel( s20 ),
    .in_0( 8'b0 ),
    .in_1( s43 ),
    .out( s27 )
  );
  assign s54[0] = s46;
  assign s54[1] = s47;
  assign s54[2] = s48;
  assign s54[3] = s49;
  assign s54[4] = s50;
  assign s54[5] = s51;
  assign s54[6] = s52;
  assign s54[7] = s53;
  assign s38 = ~ s19;
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i18 (
    .sel( s38 ),
    .in_0( s39 ),
    .in_1( s27 ),
    .out( s32 )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i19 (
    .sel( s20 ),
    .in_0( 8'b0 ),
    .in_1( s54 ),
    .out( s55 )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i20 (
    .sel( s18 ),
    .in_0( s27 ),
    .in_1( s58 ),
    .out( s25 )
  );
  assign s33 = (s55[3] | s19);
  assign s26 = (s18 | s55[0]);
  assign s28 = s55[1];
  assign s30 = s55[2];
  assign s34 = s55[4];
  assign s36 = s55[5];
  assign s56 = s55[6];
  assign s57 = s55[7];
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i21 (
    .D( s25 ),
    .C( CLK ),
    .en( s26 ),
    .Q( s10 )
  );
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i22 (
    .D( s27 ),
    .C( CLK ),
    .en( s28 ),
    .Q( s29 )
  );
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i23 (
    .D( s27 ),
    .C( CLK ),
    .en( s30 ),
    .Q( s31 )
  );
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i24 (
    .D( s32 ),
    .C( CLK ),
    .en( s33 ),
    .Q( s23 )
  );
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i25 (
    .D( s27 ),
    .C( CLK ),
    .en( s34 ),
    .Q( s35 )
  );
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i26 (
    .D( s27 ),
    .C( CLK ),
    .en( s36 ),
    .Q( s37 )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i27 (
    .sel( s56 ),
    .in_0( 8'b0 ),
    .in_1( s27 ),
    .out( OUT )
  );
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i28 (
    .D( s27 ),
    .C( CLK ),
    .en( s57 ),
    .Q( s42 )
  );
  CONDITION CONDITION_i29 (
    .INSTRUCTION( s16 ),
    .IN( s23 ),
    .OUT( s24 )
  );
  assign s11 = (s21 & s24);
endmodule
