-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_Register is
  
  port (
    Q: out std_logic;
    D: in std_logic;
    C: in std_logic;
    en: in std_logic );
end DIG_Register;

architecture Behavioral of DIG_Register is
  signal state : std_logic := '0';
begin
   Q <= state;

   process ( C )
   begin
      if rising_edge(C) and (en='1') then
        state <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_1 is
  port (
    p_out: out std_logic;
    sel: in std_logic;
    
    in_0: in std_logic;
    in_1: in std_logic );
end MUX_GATE_1;

architecture Behavioral of MUX_GATE_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      '0' when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;

entity DIG_Counter is
  generic ( Bits: integer ); 
  port (
    p_out: out std_logic_vector((Bits-1) downto 0);
    ovf: out std_logic;
    C: in std_logic;
    en: in std_logic;
    clr: in std_logic );
end DIG_Counter;

architecture Behavioral of DIG_Counter is
   signal count : std_logic_vector((Bits-1) downto 0) := (others => '0');
begin
    process (C, clr, en)
    begin
      if rising_edge(C) then
        if clr='1' then
          count <= (others => '0');
        elsif en='1' then
          count <= count + 1;
        end if;
      end if;
    end process;

    p_out <= count;
    ovf <= en when count = ((2**Bits)-1) else '0';
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_Register_BUS is
  generic ( Bits: integer ); 
  port (
    Q: out std_logic_vector ((Bits-1) downto 0);
    D: in std_logic_vector ((Bits-1) downto 0);
    C: in std_logic;
    en: in std_logic );
end DIG_Register_BUS;

architecture Behavioral of DIG_Register_BUS is
  signal state : std_logic_vector ((Bits-1) downto 0) := (others => '0');
begin
   Q <= state;

   process ( C )
   begin
      if rising_edge(C) and (en='1') then
        state <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_1 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_1;

architecture Behavioral of MUX_GATE_BUS_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity DIG_BlockRAMDualPort is
  generic (
    Bits : integer;       
    AddrBits : integer ); 
  port (
    D: out std_logic_vector ((Bits-1) downto 0);
    A: in std_logic_vector ((AddrBits-1) downto 0);
    Din: in std_logic_vector ((Bits-1) downto 0);
    str: in std_logic;
    C: in std_logic );
end DIG_BlockRAMDualPort;

architecture Behavioral of DIG_BlockRAMDualPort is
    type memoryType is array(0 to (2**AddrBits)-1) of std_logic_vector((Bits-1) downto 0);
    signal memory : memoryType;
    signal rData : std_logic_vector ((Bits-1) downto 0) := (others => '0');
begin
  process ( C )
  begin
    if rising_edge(C) then
      rData <= memory(to_integer(unsigned(A)));
      if str='1' then
        memory(to_integer(unsigned(A))) <= Din;
      end if;
    end if;
  end process;
  D <= rData;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;
use ieee.numeric_std.all;

entity DIG_CounterPreset is
  generic ( Bits: integer;
            maxValue: integer );
  port (
    p_out : out std_logic_vector((Bits-1) downto 0);
    ovf : out std_logic;
    C   : in std_logic;
    en  : in std_logic;
    clr : in std_logic;
    dir : in std_logic;
    p_in  : in std_logic_vector((Bits-1) downto 0);
    ld  : in std_logic );
end DIG_CounterPreset;

architecture Behavioral of DIG_CounterPreset is
   signal count : std_logic_vector((Bits-1) downto 0) := (others => '0');

   function maxVal ( maxv : integer )
       return integer is variable m : integer;
   begin
      if (maxv = 0) then
        m := (2**Bits)-1;
      else
        m := maxv;
      end if;
      return m;
   end function maxVal;

begin
    process (C, en)
    begin
      if rising_edge(C) then
        if clr='1' then
          count <= (others => '0');
        elsif ld='1' then
          count <= p_in;
        elsif en='1' then
          if dir='0' then
            if count=maxVal(maxValue) then
              count <= (others => '0');
            else
              count <= count + 1;
            end if;
          else
            if count=0 then
              count <= std_logic_vector(to_unsigned(maxVal(maxValue), Bits));
            else
              count <= count - 1;
            end if;
          end if;
        end if;
      end if;
    end process;

    p_out <= count;
    ovf <= en when (count = maxVal(maxValue) and dir='0') OR
                   (count = 0 and dir='1') else '0';
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_3 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic_vector (2 downto 0);
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0);
    in_2: in std_logic_vector ((Bits-1) downto 0);
    in_3: in std_logic_vector ((Bits-1) downto 0);
    in_4: in std_logic_vector ((Bits-1) downto 0);
    in_5: in std_logic_vector ((Bits-1) downto 0);
    in_6: in std_logic_vector ((Bits-1) downto 0);
    in_7: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_3;

architecture Behavioral of MUX_GATE_BUS_3 is
begin
  with sel select
    p_out <=
      in_0 when "000",
      in_1 when "001",
      in_2 when "010",
      in_3 when "011",
      in_4 when "100",
      in_5 when "101",
      in_6 when "110",
      in_7 when "111",
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DECODER_2 is
  port (
    out_0: out std_logic;
    out_1: out std_logic;
    out_2: out std_logic;
    out_3: out std_logic;
    sel: in std_logic_vector (1 downto 0) );
end DECODER_2;

architecture Behavioral of DECODER_2 is
begin
  out_0 <= '1' when sel = "00" else '0';
  out_1 <= '1' when sel = "01" else '0';
  out_2 <= '1' when sel = "10" else '0';
  out_3 <= '1' when sel = "11" else '0';
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DECODER_3 is
  port (
    out_0: out std_logic;
    out_1: out std_logic;
    out_2: out std_logic;
    out_3: out std_logic;
    out_4: out std_logic;
    out_5: out std_logic;
    out_6: out std_logic;
    out_7: out std_logic;
    sel: in std_logic_vector (2 downto 0) );
end DECODER_3;

architecture Behavioral of DECODER_3 is
begin
  out_0 <= '1' when sel = "000" else '0';
  out_1 <= '1' when sel = "001" else '0';
  out_2 <= '1' when sel = "010" else '0';
  out_3 <= '1' when sel = "011" else '0';
  out_4 <= '1' when sel = "100" else '0';
  out_5 <= '1' when sel = "101" else '0';
  out_6 <= '1' when sel = "110" else '0';
  out_7 <= '1' when sel = "111" else '0';
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;

entity DIG_Add is
  generic ( Bits: integer ); 
  port (
    s: out std_logic_vector((Bits-1) downto 0);
    c_o: out std_logic;
    a: in std_logic_vector((Bits-1) downto 0);
    b: in std_logic_vector((Bits-1) downto 0);
    c_i: in std_logic );
end DIG_Add;

architecture Behavioral of DIG_Add is
   signal temp : std_logic_vector(Bits downto 0);
begin
   temp <= ('0' & a) + b + c_i;

   s    <= temp((Bits-1) downto 0);
   c_o  <= temp(Bits);
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;

entity DIG_Sub is
  generic ( Bits: integer ); 
  port (
    s: out std_logic_vector((Bits-1) downto 0);
    c_o: out std_logic;
    a: in std_logic_vector((Bits-1) downto 0);
    b: in std_logic_vector((Bits-1) downto 0);
    c_i: in std_logic );
end DIG_Sub;

architecture Behavioral of DIG_Sub is
   signal temp : std_logic_vector(Bits downto 0);
begin
   temp <= ('0' & a) - b - c_i;

   s    <= temp((Bits-1) downto 0);
   c_o  <= temp(Bits);
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity ALU_OVERTURE is
  port (
    INSTRUCTION: in std_logic_vector(7 downto 0);
    IN1: in std_logic_vector(7 downto 0);
    IN2: in std_logic_vector(7 downto 0);
    p_OUT: out std_logic_vector(7 downto 0));
end ALU_OVERTURE;

architecture Behavioral of ALU_OVERTURE is
  signal s0: std_logic_vector(2 downto 0);
  signal s1: std_logic_vector(7 downto 0);
  signal s2: std_logic_vector(7 downto 0);
  signal s3: std_logic_vector(7 downto 0);
  signal s4: std_logic_vector(7 downto 0);
  signal s5: std_logic_vector(7 downto 0);
  signal s6: std_logic_vector(7 downto 0);
begin
  s0(0) <= INSTRUCTION(0);
  s0(1) <= INSTRUCTION(1);
  s0(2) <= INSTRUCTION(2);
  s1 <= (IN1 OR IN2);
  s2 <= NOT (IN1 AND IN2);
  s3 <= NOT (IN1 OR IN2);
  s4 <= (IN1 AND IN2);
  gate0: entity work.DIG_Add
    generic map (
      Bits => 8)
    port map (
      a => IN1,
      b => IN2,
      c_i => '0',
      s => s5);
  gate1: entity work.DIG_Sub
    generic map (
      Bits => 8)
    port map (
      a => IN1,
      b => IN2,
      c_i => '0',
      s => s6);
  gate2: entity work.MUX_GATE_BUS_3
    generic map (
      Bits => 8)
    port map (
      sel => s0,
      in_0 => s1,
      in_1 => s2,
      in_2 => s3,
      in_3 => s4,
      in_4 => s5,
      in_5 => s6,
      in_6 => "00000000",
      in_7 => "00000000",
      p_out => p_OUT);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
entity COMP_GATE_SIGNED is
  generic ( Bits : integer );
  port (
    gr: out std_logic;
    eq: out std_logic;
    le: out std_logic;
    a: in std_logic_vector ((Bits-1) downto 0);
    b: in std_logic_vector ((Bits-1) downto 0) );
end COMP_GATE_SIGNED;

architecture Behavioral of COMP_GATE_SIGNED is
begin
  process(a, b)
  begin
    if (signed(a) > signed(b)) then
      le <= '0';
      eq <= '0';
      gr <= '1';
    elsif (signed(a) < signed(b)) then
      le <= '1';
      eq <= '0';
      gr <= '0';
    else
      le <= '0';
      eq <= '1';
      gr <= '0';
    end if;
  end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_3 is
  port (
    p_out: out std_logic;
    sel: in std_logic_vector (2 downto 0);
    
    in_0: in std_logic;
    in_1: in std_logic;
    in_2: in std_logic;
    in_3: in std_logic;
    in_4: in std_logic;
    in_5: in std_logic;
    in_6: in std_logic;
    in_7: in std_logic );
end MUX_GATE_3;

architecture Behavioral of MUX_GATE_3 is
begin
  with sel select
    p_out <=
      in_0 when "000",
      in_1 when "001",
      in_2 when "010",
      in_3 when "011",
      in_4 when "100",
      in_5 when "101",
      in_6 when "110",
      in_7 when "111",
      '0' when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity CONDITION is
  port (
    INSTRUCTION: in std_logic_vector(7 downto 0);
    p_IN: in std_logic_vector(7 downto 0);
    p_OUT: out std_logic);
end CONDITION;

architecture Behavioral of CONDITION is
  signal s0: std_logic_vector(2 downto 0);
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
begin
  s0(0) <= INSTRUCTION(0);
  s0(1) <= INSTRUCTION(1);
  s0(2) <= INSTRUCTION(2);
  gate0: entity work.COMP_GATE_SIGNED
    generic map (
      Bits => 8)
    port map (
      a => p_IN,
      b => "00000000",
      gr => s1,
      eq => s2,
      le => s3);
  s4 <= (s3 OR s2);
  s5 <= NOT s2;
  s6 <= (s1 OR s2);
  gate1: entity work.MUX_GATE_3
    port map (
      sel => s0,
      in_0 => '0',
      in_1 => s2,
      in_2 => s3,
      in_3 => s4,
      in_4 => '1',
      in_5 => s5,
      in_6 => s6,
      in_7 => s1,
      p_out => p_OUT);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    p_IN: in std_logic_vector(7 downto 0);
    p_NEXT: in std_logic;
    EXE: in std_logic;
    CLK: in std_logic;
    p_OUT: out std_logic_vector(7 downto 0));
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic_vector(7 downto 0);
  signal s5: std_logic_vector(7 downto 0);
  signal s6: std_logic;
  signal s7: std_logic_vector(7 downto 0);
  signal s8: std_logic;
  signal s9: std_logic_vector(7 downto 0);
  signal s10: std_logic_vector(7 downto 0);
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic_vector(7 downto 0);
  signal s17: std_logic_vector(1 downto 0);
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal s22: std_logic;
  signal s23: std_logic_vector(7 downto 0);
  signal s24: std_logic;
  signal s25: std_logic_vector(7 downto 0);
  signal s26: std_logic;
  signal s27: std_logic_vector(7 downto 0);
  signal s28: std_logic;
  signal s29: std_logic_vector(7 downto 0);
  signal s30: std_logic;
  signal s31: std_logic_vector(7 downto 0);
  signal s32: std_logic_vector(7 downto 0);
  signal s33: std_logic;
  signal s34: std_logic;
  signal s35: std_logic_vector(7 downto 0);
  signal s36: std_logic;
  signal s37: std_logic_vector(7 downto 0);
  signal s38: std_logic;
  signal s39: std_logic_vector(7 downto 0);
  signal s40: std_logic_vector(2 downto 0);
  signal s41: std_logic_vector(7 downto 0);
  signal s42: std_logic_vector(7 downto 0);
  signal s43: std_logic_vector(7 downto 0);
  signal s44: std_logic_vector(2 downto 0);
  signal s45: std_logic;
  signal s46: std_logic;
  signal s47: std_logic;
  signal s48: std_logic;
  signal s49: std_logic;
  signal s50: std_logic;
  signal s51: std_logic;
  signal s52: std_logic;
  signal s53: std_logic_vector(7 downto 0);
  signal s54: std_logic_vector(7 downto 0);
  signal s55: std_logic;
  signal s56: std_logic_vector(7 downto 0);
begin
  gate0: entity work.DIG_Register
    port map (
      D => '1',
      C => EXE,
      en => '1',
      Q => s12);
  gate1: entity work.DIG_Register
    port map (
      D => '1',
      C => CLK,
      en => '1',
      Q => s13);
  gate2: entity work.DIG_Register
    port map (
      D => s13,
      C => CLK,
      en => '1',
      Q => s14);
  s22 <= NOT s12;
  s15 <= ('1' AND (s13 AND NOT s14));
  s0 <= (s15 OR p_NEXT);
  s8 <= (s12 OR s15);
  gate3: entity work.DIG_Register
    port map (
      D => s0,
      C => CLK,
      en => '1',
      Q => s1);
  gate4: entity work.MUX_GATE_1
    port map (
      sel => s8,
      in_0 => s0,
      in_1 => '0',
      p_out => s6);
  gate5: entity work.DIG_Register
    port map (
      D => s1,
      C => CLK,
      en => '1',
      Q => s2);
  s3 <= (NOT s1 AND s2);
  gate6: entity work.DIG_Counter
    generic map (
      Bits => 8)
    port map (
      en => '1',
      C => s3,
      clr => '0',
      p_out => s4);
  gate7: entity work.DIG_Register_BUS
    generic map (
      Bits => 8)
    port map (
      D => p_IN,
      C => s3,
      en => '1',
      Q => s43);
  gate8: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s12,
      in_0 => "00000000",
      in_1 => s43,
      p_out => s41);
  gate9: entity work.DIG_BlockRAMDualPort
    generic map (
      Bits => 8,
      AddrBits => 8)
    port map (
      A => s5,
      Din => p_IN,
      str => s6,
      C => CLK,
      D => s7);
  gate10: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s8,
      in_0 => s4,
      in_1 => s9,
      p_out => s5);
  gate11: entity work.DIG_CounterPreset
    generic map (
      Bits => 8,
      maxValue => 0)
    port map (
      en => s8,
      C => s3,
      dir => '0',
      p_in => s10,
      ld => s11,
      clr => '0',
      p_out => s9);
  gate12: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s22,
      in_0 => s7,
      in_1 => "00000000",
      p_out => s16);
  gate13: entity work.MUX_GATE_BUS_3
    generic map (
      Bits => 8)
    port map (
      sel => s40,
      in_0 => s10,
      in_1 => s29,
      in_2 => s31,
      in_3 => s23,
      in_4 => s35,
      in_5 => s37,
      in_6 => s41,
      in_7 => "00000000",
      p_out => s42);
  s56(5 downto 0) <= s16(5 downto 0);
  s56(6) <= '0';
  s56(7) <= '0';
  s17 <= s16(7 downto 6);
  s40 <= s16(5 downto 3);
  s44 <= s16(2 downto 0);
  gate14: entity work.DECODER_2
    port map (
      sel => s17,
      out_0 => s18,
      out_1 => s19,
      out_2 => s20,
      out_3 => s21);
  gate15: entity work.DECODER_3
    port map (
      sel => s44,
      out_0 => s45,
      out_1 => s46,
      out_2 => s47,
      out_3 => s48,
      out_4 => s49,
      out_5 => s50,
      out_6 => s51,
      out_7 => s52);
  gate16: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s20,
      in_0 => "00000000",
      in_1 => s42,
      p_out => s27);
  s53(0) <= s45;
  s53(1) <= s46;
  s53(2) <= s47;
  s53(3) <= s48;
  s53(4) <= s49;
  s53(5) <= s50;
  s53(6) <= s51;
  s53(7) <= s52;
  s38 <= NOT s19;
  gate17: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s20,
      in_0 => "00000000",
      in_1 => s53,
      p_out => s54);
  gate18: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s18,
      in_0 => s27,
      in_1 => s56,
      p_out => s25);
  s33 <= (s54(3) OR s19);
  s26 <= (s18 OR s54(0));
  s28 <= s54(1);
  s30 <= s54(2);
  s34 <= s54(4);
  s36 <= s54(5);
  s55 <= s54(6);
  gate19: entity work.DIG_Register_BUS
    generic map (
      Bits => 8)
    port map (
      D => s25,
      C => CLK,
      en => s26,
      Q => s10);
  gate20: entity work.DIG_Register_BUS
    generic map (
      Bits => 8)
    port map (
      D => s27,
      C => CLK,
      en => s28,
      Q => s29);
  gate21: entity work.DIG_Register_BUS
    generic map (
      Bits => 8)
    port map (
      D => s27,
      C => CLK,
      en => s30,
      Q => s31);
  gate22: entity work.DIG_Register_BUS
    generic map (
      Bits => 8)
    port map (
      D => s27,
      C => CLK,
      en => s34,
      Q => s35);
  gate23: entity work.DIG_Register_BUS
    generic map (
      Bits => 8)
    port map (
      D => s27,
      C => CLK,
      en => s36,
      Q => s37);
  gate24: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s55,
      in_0 => "00000000",
      in_1 => s27,
      p_out => p_OUT);
  gate25: entity work.ALU_OVERTURE
    port map (
      INSTRUCTION => s16,
      IN1 => s29,
      IN2 => s31,
      p_OUT => s39);
  gate26: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s38,
      in_0 => s39,
      in_1 => s27,
      p_out => s32);
  gate27: entity work.DIG_Register_BUS
    generic map (
      Bits => 8)
    port map (
      D => s32,
      C => CLK,
      en => s33,
      Q => s23);
  gate28: entity work.CONDITION
    port map (
      INSTRUCTION => s16,
      p_IN => s23,
      p_OUT => s24);
  s11 <= (s21 AND s24);
end Behavioral;
